### ISSUE TITLE
Is it possible to add Clone & Copy trait for graph::Atom?

### ISSUE THREAD

**Issue by rogerwq** [rapodaca/purr#26]
For example, I would like to sort  a vec of type Vec<Atom> by the values from another vec. This task seems challenging without the Copy trait  for Atom.

**Comment by rapodaca** [comment]
Yes, I think it's possible. But I'm not sure I understand the use case. Can you offer some example code?

**Comment by rogerwq** [comment]
Yes, here is the example code

```Rust
    fn test() -> Result<(), purr::read::Error> {
        let mut builder = purr::graph::Builder::new();
        purr::read::read("CC(=O)N", &mut builder, None)?;
        let atoms = builder.build().expect("atoms");
        let rankings: Vec<usize> = vec![4,2,3,1];

        let mut ranking_atom_tuples = rankings.iter().zip(atoms).collect::<Vec<(_,_)>>();
        ranking_atom_tuples.sort_by(|a, b| a.0.cmp(b.0));
        let new_atoms: Vec<purr::graph::Atom> = ranking_atom_tuples.iter().map(|ra| ra.1).collect();

        Ok(())
    }
```

And here is the error message
```
let new_atoms: Vec<purr::graph::Atom> = ranking_atom_tuples.iter().map(|ra| ra.1).collect();
    |                                                                       ^^^^ move occurs because `ra.1` has type `purr::graph::Atom`, which does not implement the `Copy` trait
```

To be more precisely, the feature I need is that I can change the order of the Vec atoms. However,another caveat could be that if the order changes, the Vec bonds of each atom should be updated according to the new order since the field Bond.tid depends on the atom index.

**Comment by rapodaca** [comment]
`into_iter` resolves the issue for me:

```rust
    fn test() -> Result<(), purr::read::Error> {
        let mut builder = purr::graph::Builder::new();
        purr::read::read("CC(=O)N", &mut builder, None)?;
        let atoms = builder.build().expect("atoms");
        let rankings: Vec<usize> = vec![4,2,3,1];
    
        let mut ranking_atom_tuples = rankings.iter().zip(atoms).collect::<Vec<(_,_)>>();
        ranking_atom_tuples.sort_by(|a, b| a.0.cmp(b.0));
        let new_atoms: Vec<purr::graph::Atom> = ranking_atom_tuples.into_iter().map(|ra| ra.1).collect();
    
        Ok(())
    }
```

> To be more precise, the feature I need is that I can change the order of the Vec atoms. However,another caveat could be that if the order changes, the Vec bonds of each atom should be updated according to the new order since the field Bond.tid depends on the atom index.

This is the trickier part. Canonicalization could be one application, but that's not within scope at the moment. Did you have another application in mind?

If you just want to customize the atom ordering, I think you could use the `ranking` array to update the bond target ids (Bond.tid). Iterate over each atom, and for each bond, replace the current target id (`bond.tid`) with `ranking[bond.tid]`. To re-use your previous code, it might go something like this:

```rust
    fn reorder(atoms: Vec<purr::graph::Atom>, rankings: Vec<usize>) -> Vec<purr::graph::Atom> {
        let mut ranking_atom_tuples = rankings.iter().zip(atoms).collect::<Vec<(_,_)>>();

        ranking_atom_tuples.sort_by(|a, b| a.0.cmp(b.0));

        let mut result = ranking_atom_tuples.into_iter().map(|ra| ra.1).collect::<Vec<_>>();

        for atom in &mut result {
            for bond in &mut atom.bonds {
                bond.tid = rankings[bond.tid]
            }
        }

        result
    }
```

**Comment by rogerwq** [comment]
Thank you, the solution you provided works for me.

> This is the trickier part. Canonicalization could be one application, but that's not within scope at the moment. Did you have another application in mind?
I agree. Actually, I am working on the canonicalization.

**Comment by rapodaca** [comment]
Thanks. I'll close this issue as it appears to be resolved. I'd be interested in progress you make on canonicalization.

**Comment by rogerwq** [comment]
Thanks for the attention. I will share the progress with you if I get a promising result of test.
